### ISSUE TITLE
Error: Cannot find module './freezeObject.js'

### ISSUE THREAD

**Issue by pierreglibert** [CesiumGS/gltf-pipeline#529]
Hi community :)
I have an error : 
Error: Cannot find module './freezeObject.js'
at Object.<anonymous> (....../node_modules/cesium/Source/Core/defaultValue.js:1)

```
var gltfPipeline = require('gltf-pipeline'),
    fs = require('fs');

var file = fs.readFileSync('./test/sample/dev/gltf/sample/cube_textGPU.gltf')
    processGltf = gltfPipeline.processGltf,
    gltfJSON = JSON.parse(file),
    options = {
        dracoOptions: {
            compressionLevel: 7
        }
    };

processGltf(gltfJSON, options).then( (results) => {
        fs.appendFileSync('./test/sample/dev/gltf/sample/cube_textGPU.gltf', results.gltf);
});
```

Can you help me please ?

**Comment by pierreglibert** [comment]
It seem we must to install it globally (-g).
No way to install it locally in node_module project directory ?

**Comment by lilleyse** [comment]
@pierreglibert what version of gltf-pipeline are you using? If you're using the npm package try using 2.1.8. Otherwise if you're running from source delete your `node_modules` directory and run `npm install`.

The error you're seeing is due to a change in `cesium`, one of gltf-pipeline's dependencies. It should be fixed once you update with either of the two approaches above.

**Comment by pierreglibert** [comment]
Hi @lilleyse ,
Thanks, it works :)
I already had 2.1.8 ... I just remove the node_module directory and reinstall all dep.

Have a nice day,
Pierre.
