### ISSUE TITLE
Has texture compression support been removed?

### ISSUE THREAD

**Issue by markschlosseratbentley** [CesiumGS/gltf-pipeline#564]
The latest version of the README for this tool no longer has any mention of the --texcomp texture compression options which were mentioned in this blog post: https://cesium.com/blog/2017/02/06/texture-compression/

Is this no longer supported by the gltf-pipeline tool?

Looking through the source, it seems like mentions of --texcomp were removed from the README when support for glTF 2.0 was first added, yet the internal compression code remained intact.

The latest version appears to no longer have any --texcomp logic in it.

Does the latest version of this tool support compressing textures to formats like DXT?

**Comment by lilleyse** [comment]
The texture compression code was removed during the upgrade to glTF 2.0 because at the time there wasn't a standard way to use compressed textures in a glTF and we didn't want to maintain the `image.extras.compressedImage3DTiles` object that we created for it, however some code did remain for handling assets that had used compressed textures. But as of https://github.com/CesiumGS/gltf-pipeline/pull/550 all compressed texture handling has been removed.

gltf-pipeline may eventually support KTX2/Basis for compressed textures and the issue for that is here: https://github.com/CesiumGS/gltf-pipeline/issues/551

**Comment by markschlosseratbentley** [comment]
Thanks for the explanation!
