### ISSUE TITLE
Draco compression breaks EXT_mesh_features and EXT_structural metadata

### ISSUE THREAD

**Issue by balazsdukai** [CesiumGS/gltf-pipeline#629]
I'm trying to compress gltf files with metadata for 3D Tiles v1.1 (EXT_mesh_features and EXT_structural metadata extensions).
The compression does happen and the output is a valid file (using gltf-validator), but Cesium does not load the compressed glb-s anymore.
I've seen https://github.com/CesiumGS/gltf-pipeline/pull/616 , so I thought that the compression is compatible with these two extensions.

The command `gltf-pipeline -i input.glb -o output.glb -d`. Also tried with `--keepUnusedElements`, but the result is the same.

**Comment by javagl** [comment]
This may be a specific instance of https://github.com/CesiumGS/gltf-pipeline/issues/579 

I tried to test this, with different models (and even created a new model that is similar to the [`FeatureIdAttributeAndPropertyTable`](https://github.com/CesiumGS/3d-tiles-samples/tree/main/glTF/EXT_structural_metadata/FeatureIdAttributeAndPropertyTable) model, but with more complex geometry), but could not reproduce the issue. I still don't know what _exactly_ the conditions are for Draco to modify the indices.

If you could provide one of the input models (i.e. if it can be shared and has a "reasonable" size in its uncompressed form), then I could give it a try.

Otherwise, you might want to try to add the `--draco.compressionLevel=0` parameter to the command line. This should still apply _some_ compression, but should cause Draco to retain the index order, which is currently required for the `EXT_mesh_features` extension to work.
